FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -DskipTests package

FROM eclipse-temurin:21-jre
# DODANA LINIJKA: Instalacja curl na potrzeby Docker Healthcheck
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar
COPY --from=build /app/src/main/resources/db/migration /app/db/migration

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]