server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rescue_pawtrol}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:password123}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/rescuepawtrol
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/rescuepawtrol/protocol/openid-connect/certs