# Port to teraz domy?lne 5432 (Twój lokalny PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5434/rescue_pawtrol

# Twój lokalny u?ytkownik (przy instalacji PostgreSQL domy?lnie to zawsze 'postgres')
spring.datasource.username=admin

# Has?o, które podawa?a? podczas instalacji PostgreSQL na swoim systemie Windows
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tajny klucz JWT (min. 256 bitów / 32 znaki)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970